name: Autograding Tests

'on':
- push
- repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Hello NLP script
      id: hello-nlp-script
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Hello NLP script
        setup-command: python -m pip install --upgrade pip pip install -r requirements.txt
        command: python src/hello_nlp.py
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HELLO-NLP-SCRIPT_RESULTS: "${{steps.hello-nlp-script.outputs.result}}"
      with:
        runners: hello-nlp-script
